# Generated by Django 4.1.1 on 2023-07-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username_name',
            new_name='username',
        ),
    ]
