# Generated by Django 4.1.1 on 2023-07-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_cartitem_cartsitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='cart_id',
            new_name='carts_id',
        ),
        migrations.RenameField(
            model_name='cartsitem',
            old_name='cart',
            new_name='carts',
        ),
    ]
